const app = document.getElementById('app');
const catEl = document.getElementById('cat-easter-egg');
const pianoEl = document.getElementById('piano-easter-egg');
const pianoToast = document.getElementById('piano-toast');

const state = {
  visitedProperties: new Set(JSON.parse(localStorage.getItem('visitedProperties') || '[]')),
  visitedClusters: new Set(JSON.parse(localStorage.getItem('visitedClusters') || '[]')),
  coreUnlocked: JSON.parse(localStorage.getItem('coreUnlocked') || 'false'),
  soundEnabled: JSON.parse(localStorage.getItem('soundEnabled') || 'false'),
  pianoSeedUnlocked: JSON.parse(localStorage.getItem('pianoSeedUnlocked') || 'false'),
  pianoVisible: false,
  pianoStep: 0,
  pianoAvailableOnPage: true
};
const systemMessages = ['archive refuses linear reading','language coverage: insufficient','this property has no stable boundary','memory rendered with missing pixels','classification attempt delayed'];
const audioContext = new (window.AudioContext || window.webkitAudioContext)();
const pianoSequence = [["A1","A2","A3"],["G#1","G#2","G#3"],["C#1","C#2","C#3"],["E3","G#3","C#4","E4","G#4","C#5"],["G#3","B3","E4","G#4","B4","E5"],["G3","A#3","D#4","G4","A#4","D#5"],["A1","A2","A3"],["F#3","C4","D4","F#4","A4","D5"],["G#1","G#2","G#3"],["D#3","F#3","C4","D#4","F#4","C5"],["C#1","C#2","C#3"],["E3","G#3","C#4","E4","G#4","C#5"],["G#3","B3","E4","G#4","B4","E5"],["G3","A#3","D#4","G4","A#4","D#5"],["A1","A2","A3"],["F#3","C4","D4","F#4","A4","D5"],["G#1","G#2","G#3"],["D#3","F#3","C4","D#4","F#4","C5"],["C#1","C#2","C#3"],["E3","G#3","C#4","E4","G#4","C#5"],["B3","C#4","G#4","B4","C#5","G#5"],["A3","C#4","F#4","A4","C#5","F#5"],["C#2","C#3","C#4"]];

function saveState(){localStorage.setItem('visitedProperties',JSON.stringify([...state.visitedProperties]));localStorage.setItem('visitedClusters',JSON.stringify([...state.visitedClusters]));localStorage.setItem('coreUnlocked',JSON.stringify(state.coreUnlocked));localStorage.setItem('soundEnabled',JSON.stringify(state.soundEnabled));localStorage.setItem('pianoSeedUnlocked',JSON.stringify(state.pianoSeedUnlocked));}
function renderBoot(){app.innerHTML=`<section class="panel"><h1>properties.db <span class="cursor"></span></h1><p class="subtitle">свойства, для которых не нашлось языка</p><div id="boot-lines"></div><button class="btn" id="enter-btn" style="display:none">[ enter archive ]</button></section>`;const lines=['properties.db loading...','entries found: 29','classification: incomplete','language coverage: insufficient','navigation mode: labyrinth'];let i=0;const box=document.getElementById('boot-lines');const timer=setInterval(()=>{if(i>=lines.length){clearInterval(timer);document.getElementById('enter-btn').style.display='inline-block';return;}box.innerHTML+=`<p class='term-line'>${lines[i++]}</p>`},280);document.getElementById('enter-btn').onclick=()=>{state.soundEnabled=true;saveState();renderMap();};}
function progressLine(){const touched=[...state.visitedClusters].filter(c=>c!=='core').length;return `visible entries: ${String(state.visitedProperties.size).padStart(2,'0')} / 29\nclusters touched: ${touched} / 6\ncore status: ${state.coreUnlocked?'available':'locked'}`;}
function renderMap(){checkCoreUnlock();hidePianoImmediate();app.innerHTML=`<section class='panel'><h2>map://labyrinth</h2><pre>${progressLine()}</pre><div class='grid map-grid'>${clusters.map(c=>`<div class='cluster-card ${c.id==='core'&&!state.coreUnlocked?'locked':''}'><h3>${c.title}</h3><p class='muted'>${c.subtitle}</p><button class='btn' data-cluster='${c.id}'>open</button></div>`).join('')}</div><div class='actions'><button class='btn' id='reset'>[ reset archive state ]</button></div><div style='margin-top:10px'><input class='terminal-input' id='terminal-input' placeholder='> _'></div><div id='terminal-log' class='muted'></div></section>`;
  document.querySelectorAll('[data-cluster]').forEach(b=>b.onclick=()=>renderCluster(b.dataset.cluster));
  document.getElementById('terminal-input').addEventListener('keydown',e=>{if(e.key==='Enter') handleTerminalCommand(e.target.value.trim())});
  document.getElementById('reset').onclick=()=>{if(confirm('reset archive state?')){localStorage.clear();location.reload();}};
}
function renderCluster(clusterId){const cl=clusters.find(x=>x.id===clusterId);if(clusterId==='core'&&!state.coreUnlocked)return;hidePianoImmediate();state.visitedClusters.add(clusterId);saveState();const entries=properties.filter(p=>cl.entries.includes(p.id));app.innerHTML=`<section class='panel'><h2>/path/${cl.id}</h2><p class='muted'>entries: ${entries.length}</p><div class='grid'>${entries.map(p=>`<article class='property-card'><strong>[${p.id}]</strong><h3>${p.title}</h3><p class='muted'>type: property<br>media: ${p.meta.media}<br>status: ${p.meta.signal}</p><div class='actions'><button class='btn' data-open='${p.id}'>[ open ]</button><button class='btn' data-drift='1'>[ drift ]</button><button class='btn' data-map='1'>[ map ]</button></div></article>`).join('')}</div></section>`;
  document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openProperty(b.dataset.open)); document.querySelectorAll('[data-drift]').forEach(b=>b.onclick=()=>openProperty(randomProperty().id)); document.querySelectorAll('[data-map]').forEach(b=>b.onclick=renderMap);
}
function renderSample(sample){if(sample.type==='image')return `<figure class='sample'><img src='${sample.src}' alt=''><figcaption>${sample.caption||''}</figcaption></figure>`;if(sample.type==='video')return `<figure class='sample'><video controls preload='metadata' src='${sample.src}'></video><figcaption>${sample.caption||''}</figcaption></figure>`;if(sample.type==='audio')return `<figure class='sample'><audio controls src='${sample.src}'></audio><figcaption>${sample.caption||''}</figcaption></figure>`;if(sample.type==='code')return `<div class='sample'><strong>${sample.title||'code'}</strong><pre><code>${sample.body}</code></pre></div>`;return `<div class='sample'><strong>[${sample.title||'source_fragment'}]</strong><p>${sample.body||''}</p></div>`}
function openProperty(propertyId){const p=properties.find(x=>x.id===propertyId);if(!p)return;closeModal();state.pianoAvailableOnPage=true;markVisited(propertyId);if(p.id==='p17'){state.pianoSeedUnlocked=true;saveState();}if(Math.random()<0.25)showRandomSystemMessage();if(Math.random()<0.15)showCat();const idx=properties.findIndex(x=>x.id===propertyId);const prev=properties[(idx-1+properties.length)%properties.length].id;const next=properties[(idx+1)%properties.length].id;const extra=p.id==='p28'?`<div class='sample'><strong>genome-terminal</strong><button class='btn' onclick='runGenomeAssembly()'>[run assembly]</button><pre id='genome-log'></pre></div>`:'';const final=p.id==='p29'?`<div class='sample'><pre>end of visible entries\n\nunlisted properties: many\nlanguage coverage: insufficient\nclassification attempt: abandoned\nsubject status: ongoing</pre><p style='white-space:pre-line'>${finalMessage}</p></div>`:'';
 app.insertAdjacentHTML('beforeend',`<div class='modal' id='modal'><div class='modal-content'><h2>[${p.id}] ${p.title}</h2><p class='muted'>definition:</p><p>${p.definition}</p><pre>cluster: ${p.cluster}\ntype: ${p.meta.type}\nsignal: ${p.meta.signal}\nmedia: ${p.meta.media}</pre>${p.samples.map(renderSample).join('')}${extra}<p>linked entries: ${p.links.map(x=>`[${x}]`).join(' ')}</p><div class='actions'><button class='btn' onclick='openProperty("${prev}")'>[ previous tunnel ]</button><button class='btn' onclick='openProperty("${next}")'>[ next tunnel ]</button><button class='btn' onclick='closeModal()'>[ back to cluster ]</button><button class='btn' onclick='renderMap()'>[ map ]</button><button class='btn' onclick='openProperty(randomProperty().id)'>[ random drift ]</button></div>${final}</div></div>`);
 maybeShowPiano(p.id,false);
}
function closeModal(){document.getElementById('modal')?.remove();hidePianoImmediate();}
function markVisited(propertyId){state.visitedProperties.add(propertyId);const p=properties.find(x=>x.id===propertyId);if(p)state.visitedClusters.add(p.cluster);checkCoreUnlock();saveState();}
function checkCoreUnlock(){const touched=[...state.visitedClusters].filter(c=>c!=='core');if(state.visitedProperties.size>=12||touched.length>=6){state.coreUnlocked=true;saveState();}return state.coreUnlocked;}
function showRandomSystemMessage(){const msg=systemMessages[Math.floor(Math.random()*systemMessages.length)];const el=document.createElement('div');el.className='panel';el.style.position='fixed';el.style.top='10px';el.style.right='10px';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
function showCat(force=false){if(!force&&Math.random()>0.15)return;catEl.textContent=' /\\_/\\\n( o.o )\n > ^ <';catEl.className='walk';catEl.onclick=()=>{playPurr();catEl.className='sleep';};setTimeout(()=>{if(Math.random()<0.35)catEl.className='sleep';else catEl.className='';},18000)}
function playPurr(){new Audio('assets/audio/cat-purr.mp3').play().catch(()=>alert('purr...'));}
function noteToFrequency(note){const m=note.match(/^([A-G])([b#]?)(\d)$/);const map={C:0,D:2,E:4,F:5,G:7,A:9,B:11};const semi=map[m[1]]+(m[2]==='#'?1:m[2]==='b'?-1:0);const midi=(+m[3]+1)*12+semi;return 440*Math.pow(2,(midi-69)/12)}
function playNextPianoChord(){if(!state.pianoVisible||!state.pianoAvailableOnPage)return;if(audioContext.state==='suspended')audioContext.resume();const isTail=state.pianoStep>=pianoSequence.length-4;const fadeRatio=isTail?(pianoSequence.length-state.pianoStep)/4:1;const gainBase=0.14*Math.max(.2,fadeRatio);pianoEl.style.opacity=String(0.25+0.75*Math.max(.12,fadeRatio));(pianoSequence[state.pianoStep]||[]).forEach((n,i)=>{const o=audioContext.createOscillator();const g=audioContext.createGain();o.type='triangle';o.frequency.value=noteToFrequency(n);g.gain.setValueAtTime(0.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(gainBase,audioContext.currentTime+0.04+i*0.008);g.gain.exponentialRampToValueAtTime(0.0001,audioContext.currentTime+1.15);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+1.25);});state.pianoStep++;if(state.pianoStep>=pianoSequence.length){dismissPiano();}}
function maybeShowPiano(propertyId,forced){const eligible=['p09','p28','p29'];if(!state.pianoSeedUnlocked&&!forced)return;if(!forced&&propertyId!=='p17'&&!eligible.includes(propertyId))return;if(!state.pianoAvailableOnPage)return;showPiano();}
function showPiano(){state.pianoStep=0;state.pianoVisible=true;showToast('acoustic residue detected');setTimeout(()=>pianoEl.classList.add('active'),320)}
function dismissPiano(){pianoEl.classList.add('fading');setTimeout(()=>{hidePianoImmediate();showToast('the fragment chose not to remain');state.pianoAvailableOnPage=false;},900)}
function hidePianoImmediate(){state.pianoVisible=false;pianoEl.classList.remove('active','fading');pianoEl.style.opacity='';}
function showToast(text){pianoToast.textContent=text;pianoToast.classList.add('show');setTimeout(()=>pianoToast.classList.remove('show'),2100)}
function runGenomeAssembly(){const log=document.getElementById('genome-log');if(!log)return;const lines=['$ sciaridae_assembly --input dream_reads.fastq --mode poetic','','loading raw reads...','read_001 ATGCTAGGCTAANNNCTAG','read_002 TTAACGATCGGATTA','assembling contigs...','contig_01 length: 1204 bp','contig_02 length: 807 bp','contig_03 length: unresolved','annotation: gene_01 language_shift','voice integrity: preserved','assembly complete: incomplete by design'];log.textContent='';let i=0;const t=setInterval(()=>{if(i>=lines.length)return clearInterval(t);log.textContent+=lines[i++]+'\n';},120)}
function handleTerminalCommand(command){const log=document.getElementById('terminal-log');const c=command.toLowerCase();let out='unknown command';if(c==='help')out='help | cat | dream | assembly | drift | gothic cyberpunk | core | piano';else if(c==='cat'){showCat(true);out='cat summoned';}else if(c==='dream'){const ds=properties.flatMap(p=>p.samples.filter(s=>s.type==='text'&&/dream|source/i.test(s.title||s.body)).map(s=>`${p.id}: ${s.body}`));out=ds[Math.floor(Math.random()*ds.length)]||'no dream logs yet';}else if(c==='assembly'){out='opening assembly...';openProperty('p28');setTimeout(runGenomeAssembly,100);}else if(c==='drift'){openProperty(randomProperty().id);out='drift';}else if(c==='gothic cyberpunk'){new Audio('assets/audio/gothic-cyberpunk.mp3').play().catch(()=>{});out='audio requested';}else if(c==='core'){if(state.coreUnlocked)openProperty('p29');else out='core locked: open more entries';}else if(c==='piano'){if(!state.pianoSeedUnlocked)state.pianoSeedUnlocked=true;saveState();maybeShowPiano(state.currentProperty||'p28',true);out='acoustic residue requested';}if(log)log.textContent=out}
function randomProperty(){return properties[Math.floor(Math.random()*properties.length)]}
pianoEl.addEventListener('click',playNextPianoChord);
setInterval(()=>showCat(false),70000);
renderBoot();
