const app = document.getElementById('app');
const catEl = document.getElementById('cat-easter-egg');
const pianoEl = document.getElementById('piano-easter-egg');
const pianoToast = document.getElementById('piano-toast');

const state = {
  visitedProperties: new Set(JSON.parse(localStorage.getItem('visitedProperties') || '[]')),
  visitedClusters: new Set(JSON.parse(localStorage.getItem('visitedClusters') || '[]')),
  coreUnlocked: JSON.parse(localStorage.getItem('coreUnlocked') || 'false'),
  soundEnabled: JSON.parse(localStorage.getItem('soundEnabled') || 'false'),
  pianoSeedUnlocked: JSON.parse(localStorage.getItem('pianoSeedUnlocked') || 'false'),
  pianoVisible: false,
  pianoStep: 0,
  pianoAvailableOnPage: true
};
const systemMessages = ['archive refuses linear reading','language coverage: insufficient','this property has no stable boundary','memory rendered with missing pixels','classification attempt delayed'];
const audioContext = new (window.AudioContext || window.webkitAudioContext)();
const pianoSequence = [["A1","A2","A3"],["G#1","G#2","G#3"],["C#1","C#2","C#3"],["E3","G#3","C#4","E4","G#4","C#5"],["G#3","B3","E4","G#4","B4","E5"],["G3","A#3","D#4","G4","A#4","D#5"],["A1","A2","A3"],["F#3","C4","D4","F#4","A4","D5"],["G#1","G#2","G#3"],["D#3","F#3","C4","D#4","F#4","C5"],["C#1","C#2","C#3"],["E3","G#3","C#4","E4","G#4","C#5"],["G#3","B3","E4","G#4","B4","E5"],["G3","A#3","D#4","G4","A#4","D#5"],["A1","A2","A3"],["F#3","C4","D4","F#4","A4","D5"],["G#1","G#2","G#3"],["D#3","F#3","C4","D#4","F#4","C5"],["C#1","C#2","C#3"],["E3","G#3","C#4","E4","G#4","C#5"],["B3","C#4","G#4","B4","C#5","G#5"],["A3","C#4","F#4","A4","C#5","F#5"],["C#2","C#3","C#4"]];
let anomalyCleanups = [];

function saveState(){localStorage.setItem('visitedProperties',JSON.stringify([...state.visitedProperties]));localStorage.setItem('visitedClusters',JSON.stringify([...state.visitedClusters]));localStorage.setItem('coreUnlocked',JSON.stringify(state.coreUnlocked));localStorage.setItem('soundEnabled',JSON.stringify(state.soundEnabled));localStorage.setItem('pianoSeedUnlocked',JSON.stringify(state.pianoSeedUnlocked));}
function renderBoot(){app.innerHTML=`<section class="panel"><h1>properties.db <span class="cursor"></span></h1><p class="subtitle">свойства, для которых не нашлось языка</p><div id="boot-lines"></div><button class="btn" id="enter-btn" style="display:none">[ enter archive ]</button></section>`;const lines=['properties.db loading...','entries found: 29','classification: incomplete','language coverage: insufficient','navigation mode: labyrinth'];let i=0;const box=document.getElementById('boot-lines');const timer=setInterval(()=>{if(i>=lines.length){clearInterval(timer);document.getElementById('enter-btn').style.display='inline-block';return;}box.innerHTML+=`<p class='term-line'>${lines[i++]}</p>`},280);document.getElementById('enter-btn').onclick=()=>{state.soundEnabled=true;saveState();renderMap();};}
function progressLine(){const touched=[...state.visitedClusters].filter(c=>c!=='core').length;return `visible entries: ${String(state.visitedProperties.size).padStart(2,'0')} / 29\nclusters touched: ${touched} / 6\ncore status: ${state.coreUnlocked?'available':'locked'}`;}
function renderMap(){checkCoreUnlock();hidePianoImmediate();app.innerHTML=`<section class='panel'><h2>map://labyrinth</h2><pre>${progressLine()}</pre><div class='grid map-grid'>${clusters.map(c=>`<div class='cluster-card ${c.id==='core'&&!state.coreUnlocked?'locked':''}'><h3>${c.title}</h3><p class='muted'>${c.subtitle}</p><button class='btn' data-cluster='${c.id}'>open</button></div>`).join('')}</div><div class='actions'><button class='btn' id='reset'>[ reset archive state ]</button></div><div style='margin-top:10px'><input class='terminal-input' id='terminal-input' placeholder='> _'></div><div id='terminal-log' class='muted'></div></section>`;
  document.querySelectorAll('[data-cluster]').forEach(b=>b.onclick=()=>renderCluster(b.dataset.cluster));
  document.getElementById('terminal-input').addEventListener('keydown',e=>{if(e.key==='Enter') handleTerminalCommand(e.target.value.trim())});
  document.getElementById('reset').onclick=()=>{if(confirm('reset archive state?')){localStorage.clear();location.reload();}};
}
function renderCluster(clusterId){const cl=clusters.find(x=>x.id===clusterId);if(clusterId==='core'&&!state.coreUnlocked)return;hidePianoImmediate();state.visitedClusters.add(clusterId);saveState();const entries=properties.filter(p=>cl.entries.includes(p.id));app.innerHTML=`<section class='panel'><h2>/path/${cl.id}</h2><p class='muted'>entries: ${entries.length}</p><div class='grid'>${entries.map(p=>`<article class='property-card'><strong>[${p.id}]</strong><h3>${p.title}</h3><p class='muted'>type: property<br>media: ${p.meta.media}<br>status: ${p.meta.signal}</p><div class='actions'><button class='btn' data-open='${p.id}'>[ open ]</button><button class='btn' data-drift='1'>[ drift ]</button><button class='btn' data-map='1'>[ map ]</button></div></article>`).join('')}</div></section>`;
  document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openProperty(b.dataset.open)); document.querySelectorAll('[data-drift]').forEach(b=>b.onclick=()=>openProperty(randomProperty().id)); document.querySelectorAll('[data-map]').forEach(b=>b.onclick=renderMap);
}
function renderSample(sample){if(sample.type==='image')return `<figure class='sample'><img src='${sample.src}' alt=''><figcaption>${sample.caption||''}</figcaption></figure>`;if(sample.type==='video')return `<figure class='sample'><video controls preload='metadata' src='${sample.src}'></video><figcaption>${sample.caption||''}</figcaption></figure>`;if(sample.type==='audio')return `<figure class='sample'><audio controls src='${sample.src}'></audio><figcaption>${sample.caption||''}</figcaption></figure>`;if(sample.type==='code')return `<div class='sample'><strong>${sample.title||'code'}</strong><pre><code>${sample.body}</code></pre></div>`;return `<div class='sample'><strong>[${sample.title||'source_fragment'}]</strong><p>${sample.body||''}</p></div>`}
function openProperty(propertyId){const p=properties.find(x=>x.id===propertyId);if(!p)return;state.currentProperty=propertyId;closeModal();state.pianoAvailableOnPage=true;markVisited(propertyId);if(p.id==='p17'){state.pianoSeedUnlocked=true;saveState();}if(Math.random()<0.25)showRandomSystemMessage();if(Math.random()<0.15)showCat();const idx=properties.findIndex(x=>x.id===propertyId);const prev=properties[(idx-1+properties.length)%properties.length].id;const next=properties[(idx+1)%properties.length].id;const extra=p.id==='p28'?`<div class='sample'><strong>genome-terminal</strong><button class='btn' onclick='runGenomeAssembly()'>[run assembly]</button><pre id='genome-log'></pre></div>`:'';const final=p.id==='p29'?`<div class='sample'><pre>end of visible entries\n\nunlisted properties: many\nlanguage coverage: insufficient\nclassification attempt: abandoned\nsubject status: ongoing</pre><p style='white-space:pre-line'>${finalMessage}</p></div>`:'';
 app.insertAdjacentHTML('beforeend',`<div class='modal' id='modal'><div class='modal-content'><h2>[${p.id}] ${p.title}</h2><p class='muted'>definition:</p><p>${p.definition}</p><pre>cluster: ${p.cluster}\ntype: ${p.meta.type}\nsignal: ${p.meta.signal}\nmedia: ${p.meta.media}</pre>${p.samples.map(renderSample).join('')}${extra}<p>linked entries: ${p.links.map(x=>`[${x}]`).join(' ')}</p><div class='actions'><button class='btn' onclick='openProperty("${prev}")'>[ previous tunnel ]</button><button class='btn' onclick='openProperty("${next}")'>[ next tunnel ]</button><button class='btn' onclick='closeModal()'>[ back to cluster ]</button><button class='btn' onclick='renderMap()'>[ map ]</button><button class='btn' onclick='openProperty(randomProperty().id)'>[ random drift ]</button></div>${final}</div></div>`);
 maybeShowPlantProcess(p.id); maybeShowContemporaryShadow(p.id); maybeEnableLightLeak(p.id); maybeStartCursorReflections(p.id); maybeEnableMemoryFocus(p.id);
 maybeShowPiano(p.id,p.id==='p17');
}
function closeModal(){anomalyCleanups.forEach(fn=>fn());anomalyCleanups=[];document.getElementById('modal')?.remove();hidePianoImmediate();}
function markVisited(propertyId){state.visitedProperties.add(propertyId);const p=properties.find(x=>x.id===propertyId);if(p)state.visitedClusters.add(p.cluster);checkCoreUnlock();saveState();}
function checkCoreUnlock(){const touched=[...state.visitedClusters].filter(c=>c!=='core');if(state.visitedProperties.size>=12||touched.length>=6){state.coreUnlocked=true;saveState();}return state.coreUnlocked;}
function showRandomSystemMessage(){const msg=systemMessages[Math.floor(Math.random()*systemMessages.length)];const el=document.createElement('div');el.className='panel';el.style.position='fixed';el.style.top='10px';el.style.right='10px';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
function showCat(force=false){if(!force&&Math.random()>0.15)return;catEl.textContent=' /\\_/\\\n( o.o )\n > ^ <';catEl.className='walk';catEl.onclick=()=>{playPurr();catEl.className='sleep';};setTimeout(()=>{if(Math.random()<0.35)catEl.className='sleep';else catEl.className='';},18000)}
function playPurr(){new Audio('assets/audio/cat-purr.mp3').play().catch(()=>alert('purr...'));}
function noteToFrequency(note){const m=note.match(/^([A-G])([b#]?)(\d)$/);const map={C:0,D:2,E:4,F:5,G:7,A:9,B:11};const semi=map[m[1]]+(m[2]==='#'?1:m[2]==='b'?-1:0);const midi=(+m[3]+1)*12+semi;return 440*Math.pow(2,(midi-69)/12)}
function playNextPianoChord(){if(!state.pianoVisible||!state.pianoAvailableOnPage)return;if(audioContext.state==='suspended')audioContext.resume();const isTail=state.pianoStep>=pianoSequence.length-4;const fadeRatio=isTail?(pianoSequence.length-state.pianoStep)/4:1;const gainBase=0.14*Math.max(.2,fadeRatio);pianoEl.style.opacity=String(0.25+0.75*Math.max(.12,fadeRatio));(pianoSequence[state.pianoStep]||[]).forEach((n,i)=>{const o=audioContext.createOscillator();const g=audioContext.createGain();o.type='triangle';o.frequency.value=noteToFrequency(n);g.gain.setValueAtTime(0.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(gainBase,audioContext.currentTime+0.04+i*0.008);g.gain.exponentialRampToValueAtTime(0.0001,audioContext.currentTime+1.15);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+1.25);});state.pianoStep++;if(state.pianoStep>=pianoSequence.length){dismissPiano();}}
function maybeShowPiano(propertyId,forced){const eligible=['p09','p28','p29'];if(!state.pianoSeedUnlocked&&!forced)return;if(!forced&&propertyId!=='p17'&&!eligible.includes(propertyId))return;if(!state.pianoAvailableOnPage)return;showPiano();}
function showPiano(){state.pianoStep=0;state.pianoVisible=true;showToast('acoustic residue detected');setTimeout(()=>pianoEl.classList.add('active'),320)}
function dismissPiano(){pianoEl.classList.add('fading');setTimeout(()=>{hidePianoImmediate();showToast('the fragment chose not to remain');state.pianoAvailableOnPage=false;},900)}
function hidePianoImmediate(){state.pianoVisible=false;pianoEl.classList.remove('active','fading');pianoEl.style.opacity='';}
function showToast(text){pianoToast.textContent=text;pianoToast.classList.add('show');setTimeout(()=>pianoToast.classList.remove('show'),2100)}
function runGenomeAssembly(){const log=document.getElementById('genome-log');if(!log)return;const lines=['$ sciaridae_assembly --input dream_reads.fastq --mode poetic','','loading raw reads...','read_001 ATGCTAGGCTAANNNCTAG','read_002 TTAACGATCGGATTA','assembling contigs...','contig_01 length: 1204 bp','contig_02 length: 807 bp','contig_03 length: unresolved','annotation: gene_01 language_shift','voice integrity: preserved','assembly complete: incomplete by design'];log.textContent='';let i=0;const t=setInterval(()=>{if(i>=lines.length)return clearInterval(t);log.textContent+=lines[i++]+'\n';},120)}
function handleTerminalCommand(command){const log=document.getElementById('terminal-log');const c=command.toLowerCase();let out='unknown command';if(c==='help')out='help | cat | dream | assembly | drift | gothic cyberpunk | core | piano';else if(c==='cat'){showCat(true);out='cat summoned';}else if(c==='dream'){const ds=properties.flatMap(p=>p.samples.filter(s=>s.type==='text'&&/dream|source/i.test(s.title||s.body)).map(s=>`${p.id}: ${s.body}`));out=ds[Math.floor(Math.random()*ds.length)]||'no dream logs yet';}else if(c==='assembly'){out='opening assembly...';openProperty('p28');setTimeout(runGenomeAssembly,100);}else if(c==='drift'){openProperty(randomProperty().id);out='drift';}else if(c==='gothic cyberpunk'){new Audio('assets/audio/gothic-cyberpunk.mp3').play().catch(()=>{});out='audio requested';}else if(c==='core'){if(state.coreUnlocked)openProperty('p29');else out='core locked: open more entries';}else if(c==='piano'){if(!state.pianoSeedUnlocked)state.pianoSeedUnlocked=true;saveState();maybeShowPiano(state.currentProperty||'p28',true);out='acoustic residue requested';}if(log)log.textContent=out}
function randomProperty(){return properties[Math.floor(Math.random()*properties.length)]}
function maybeShowPlantProcess(propertyId){if(!['p02','p16','p27'].includes(propertyId))return;const box=document.querySelector('#modal .modal-content');if(!box)return;const wrap=document.createElement('div');wrap.className='plant-process';wrap.innerHTML=`<svg viewBox="0 0 130 170" aria-hidden="true"><path class="plant-stem" d="M65 160 Q66 145 65 130 Q64 110 66 96 Q66 84 65 76"></path></svg>`;box.appendChild(wrap);let progress=0, doneToast=false, ended=false;const leaves=[];const leafData=[[58,152,-26],[72,145,25],[56,133,-28],[74,122,26],[57,110,-24],[73,98,25],[58,87,-20]];const makeLeaf=i=>{const leaf=document.createElement('span');leaf.className='plant-leaf';leaf.style.left=`${leafData[i][0]}px`;leaf.style.top=`${leafData[i][1]}px`;leaf.style.setProperty('--leaf-rot',`${leafData[i][2]}deg`);wrap.appendChild(leaf);leaves[i]=leaf;};
makeLeaf(0);makeLeaf(1);const onMove=e=>{const r=wrap.getBoundingClientRect();const dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2);if(Math.hypot(dx,dy)<180&&!ended)progress=Math.min(100,progress+1.3);const stem=wrap.querySelector('.plant-stem');stem.style.strokeDashoffset=`${160-Math.min(84,progress*1.6)}`;for(let i=2;i<leafData.length;i++){if(progress>(20+i*10)&&!leaves[i])makeLeaf(i);}if(progress>=100&&!doneToast){doneToast=true;wrap.classList.add('grown');showToast('the plant reached its available explanation');}};
document.addEventListener('mousemove',onMove);wrap.onclick=()=>{if(!wrap.classList.contains('grown')||ended)return;ended=true;const marks=Array.from({length:14},(_,i)=>{const m=document.createElement('span');m.className='plant-question';m.textContent='?';m.style.left=`${45+(i%7)*7}px`;m.style.top='74px';m.style.setProperty('--q-rot',`${(i%5-2)*6}deg`);m.style.animationDelay=`${i*40}ms`;wrap.appendChild(m);return m;});wrap.classList.add('disintegrate');setTimeout(()=>marks.forEach(m=>m.classList.add('settle')),1200);setTimeout(()=>marks.forEach(m=>m.classList.add('fade')),3500);showToast('the plant exceeded lexical capacity');};
anomalyCleanups.push(()=>{document.removeEventListener('mousemove',onMove);});
}
function maybeShowContemporaryShadow(propertyId){if(!['p10','p25','p29'].includes(propertyId))return;const box=document.querySelector('#modal .modal-content');if(!box)return;const fig=document.createElement('div');fig.className='shadow-figure';fig.innerHTML='<span></span>';box.appendChild(fig);let danceTime=0,last=performance.now(),moving=false,dead=false,timer;const onMove=()=>{moving=true;clearTimeout(timer);timer=setTimeout(()=>moving=false,120)};const raf=()=>{if(dead)return;const now=performance.now();const dt=now-last;last=now;if(moving&&danceTime<15000){danceTime+=dt;fig.classList.add('dancing');fig.style.setProperty('--dance-t',`${danceTime}ms`);}else fig.classList.remove('dancing');if(danceTime>=15000&&!dead){dead=true;fig.classList.add('done');showToast('shadow completed movement without body');setTimeout(()=>fig.remove(),900);}requestAnimationFrame(raf)};document.addEventListener('mousemove',onMove);requestAnimationFrame(raf);anomalyCleanups.push(()=>{dead=true;document.removeEventListener('mousemove',onMove);clearTimeout(timer);});}
function maybeEnableLightLeak(propertyId){if(!['p02','p09','p19'].includes(propertyId))return;const box=document.querySelector('#modal .modal-content');if(!box||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;box.classList.add('light-leak');const move=e=>{const r=box.getBoundingClientRect();box.style.setProperty('--mouse-x',`${e.clientX-r.left}px`);box.style.setProperty('--mouse-y',`${e.clientY-r.top}px`);box.classList.add('light-active');};const leave=()=>box.classList.remove('light-active');box.addEventListener('mousemove',move);box.addEventListener('mouseleave',leave);anomalyCleanups.push(()=>{box.classList.remove('light-leak','light-active');box.removeEventListener('mousemove',move);box.removeEventListener('mouseleave',leave);});}
function maybeStartCursorReflections(propertyId){if(!['p01','p24'].includes(propertyId))return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;showToast('cursor reflection detached');const ghosts=[...Array(3)].map((_,i)=>{const d=document.createElement('div');d.className='cursor-ghost';d.dataset.mode=String(i);document.body.appendChild(d);return d;});let pos={x:0,y:0},dead=false,start=performance.now();const trail=ghosts.map(()=>({x:0,y:0}));const move=e=>{pos={x:e.clientX,y:e.clientY};};document.addEventListener('mousemove',move);const raf=()=>{if(dead)return;ghosts.forEach((g,i)=>{const targetX=i===0?window.innerWidth-pos.x:pos.x;trail[i].x+=(targetX-trail[i].x)*(0.08+i*0.04);trail[i].y+=(pos.y-trail[i].y)*(0.08+i*0.04);g.style.transform=`translate(${trail[i].x}px,${trail[i].y}px)`;});if(performance.now()-start>10000){dead=true;ghosts.forEach(g=>g.classList.add('fade'));setTimeout(()=>ghosts.forEach(g=>g.remove()),800);}requestAnimationFrame(raf)};requestAnimationFrame(raf);anomalyCleanups.push(()=>{dead=true;document.removeEventListener('mousemove',move);ghosts.forEach(g=>g.remove());});}
function maybeEnableMemoryFocus(propertyId){if(propertyId!=='p06')return;const sample=document.querySelector('#modal .sample img');if(!sample)return;sample.classList.add('memory-focus-image');const fig=sample.closest('figure');const hint=document.createElement('figcaption');hint.className='memory-focus-caption';hint.textContent='hold to increase memory resolution';fig?.appendChild(hint);let held=false,startAt=0,done=false,progress=0,rafId;const layers=['date','place','field note'];const list=document.createElement('div');list.className='memory-focus-layers';fig?.appendChild(list);const render=()=>{if(!held)return;progress=Math.min(1,(performance.now()-startAt)/4000);sample.style.setProperty('--focus',String(progress));list.innerHTML=layers.slice(0,Math.floor(progress*layers.length)+1).map(x=>`<div>${x}</div>`).join('');if(progress>=1&&!done){done=true;showToast('image clear\nmeaning unstable');}rafId=requestAnimationFrame(render);};const down=e=>{e.preventDefault();held=true;startAt=performance.now()-(progress*4000);render();};const up=()=>{if(!held)return;held=false;cancelAnimationFrame(rafId);if(progress<1)showToast('focus interrupted');sample.style.setProperty('--focus',String(done?0.75:0.12));};sample.addEventListener('mousedown',down);sample.addEventListener('touchstart',down,{passive:false});window.addEventListener('mouseup',up);window.addEventListener('touchend',up);anomalyCleanups.push(()=>{cancelAnimationFrame(rafId);sample.removeEventListener('mousedown',down);sample.removeEventListener('touchstart',down);window.removeEventListener('mouseup',up);window.removeEventListener('touchend',up);});}
document.getElementById('piano-button')?.remove();
document.getElementById('mute-button')?.remove();
pianoEl.addEventListener('click',playNextPianoChord);
setInterval(()=>showCat(false),70000);
renderBoot();
